// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncgfsntvrieiuynyqsgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZ2ZzbnR2cmllaXV5bnlxc2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTg5NTMsImV4cCI6MjA2NTQ3NDk1M30._UBhi7Ht73R1NruvOJROkkzjpYC40s3C4F_O7jIFYnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);